on:
  push:
    branches:
      - main 

jobs:
  cov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov
    - name: Run Coverage
      run: RUST_LOG=debug cargo +nightly llvm-cov --no-cfg-coverage-nightly --text --output-dir coverage/
    - name: Commit and Push Coverage Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Update coverage results"
        git push
