name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  cov:
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@v1
      with:
        tool: cargo-llvm-cov

    - name: Run Coverage
      run: cargo +nightly llvm-cov --no-cfg-coverage-nightly --text --output-dir coverage/


      

