name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  cov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Checkout the correct branch for the PR
      with:
        ref: ${{ github.head_ref }}  # Ensures the PR source branch is checked out

    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov

    - name: Run Coverage
      run: RUST_LOG=debug cargo +nightly llvm-cov --no-cfg-coverage-nightly --text --output-dir coverage/

    - name: Commit and Push Coverage Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Update coverage results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
